<?php
/**
 * Interface por AnuncioServiceInterface.
 * Generated by antigravity
 */

namespace App\Services\Interfaces;

interface AnuncioServiceInterface
{
    public function obtenerAnunciosPaginados(int $docenteCursoId, int $perPage = 10): array;
    public function obtenerAnuncios(int $docenteCursoId): array;
    public function crearAnuncio(array $data): object;
    public function actualizarAnuncio(int $anuncioId, array $data): object;
    public function eliminarAnuncio(int $anuncioId): void;
}
